//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiDesignPatterns.Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiDesignPatterns.Mobile.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Exemple de Code.
        /// </summary>
        public static string FactoryPattern_CodeTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_CodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Plus de classes.
        /// </summary>
        public static string FactoryPattern_Cons1 {
            get {
                return ResourceManager.GetString("FactoryPattern_Cons1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Complexité augmente.
        /// </summary>
        public static string FactoryPattern_Cons2 {
            get {
                return ResourceManager.GetString("FactoryPattern_Cons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Factory peut devenir grande.
        /// </summary>
        public static string FactoryPattern_Cons3 {
            get {
                return ResourceManager.GetString("FactoryPattern_Cons3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Inconvénients.
        /// </summary>
        public static string FactoryPattern_ConsTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_ConsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creational.
        /// </summary>
        public static string FactoryPattern_Creational {
            get {
                return ResourceManager.GetString("FactoryPattern_Creational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le pattern Factory fournit une interface pour créer des objets sans exposer la logique de création au client. Il délègue l&apos;instanciation à des classes factory spécialisées..
        /// </summary>
        public static string FactoryPattern_Description {
            get {
                return ResourceManager.GetString("FactoryPattern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Description.
        /// </summary>
        public static string FactoryPattern_DescriptionTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un Véhicule.
        /// </summary>
        public static string FactoryPattern_InteractiveButton {
            get {
                return ResourceManager.GetString("FactoryPattern_InteractiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un type de véhicule et créez-le en utilisant la factory :.
        /// </summary>
        public static string FactoryPattern_InteractiveDesc {
            get {
                return ResourceManager.GetString("FactoryPattern_InteractiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Exemple Interactif.
        /// </summary>
        public static string FactoryPattern_InteractiveTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_InteractiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vélo (Bike).
        /// </summary>
        public static string FactoryPattern_PickerBike {
            get {
                return ResourceManager.GetString("FactoryPattern_PickerBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voiture (Car).
        /// </summary>
        public static string FactoryPattern_PickerCar {
            get {
                return ResourceManager.GetString("FactoryPattern_PickerCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avion (Plane).
        /// </summary>
        public static string FactoryPattern_PickerPlane {
            get {
                return ResourceManager.GetString("FactoryPattern_PickerPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un type de véhicule.
        /// </summary>
        public static string FactoryPattern_PickerTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_PickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Couplage faible.
        /// </summary>
        public static string FactoryPattern_Pros1 {
            get {
                return ResourceManager.GetString("FactoryPattern_Pros1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Facile à étendre.
        /// </summary>
        public static string FactoryPattern_Pros2 {
            get {
                return ResourceManager.GetString("FactoryPattern_Pros2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Création centralisée.
        /// </summary>
        public static string FactoryPattern_Pros3 {
            get {
                return ResourceManager.GetString("FactoryPattern_Pros3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Avantages.
        /// </summary>
        public static string FactoryPattern_ProsTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_ProsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de documents dans un logiciel de bureautique : WordFactory crée des .docx, SpreadsheetFactory crée des .xlsx - même interface, implémentations différentes..
        /// </summary>
        public static string FactoryPattern_RealWorldDesc {
            get {
                return ResourceManager.GetString("FactoryPattern_RealWorldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scénario Réel.
        /// </summary>
        public static string FactoryPattern_RealWorldTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_RealWorldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏗️ Factory Pattern.
        /// </summary>
        public static string FactoryPattern_Title {
            get {
                return ResourceManager.GetString("FactoryPattern_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quand la logique de création d&apos;objet est complexe.
        /// </summary>
        public static string FactoryPattern_WhenToUse1 {
            get {
                return ResourceManager.GetString("FactoryPattern_WhenToUse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quand vous devez découpler la création d&apos;objet de l&apos;utilisation.
        /// </summary>
        public static string FactoryPattern_WhenToUse2 {
            get {
                return ResourceManager.GetString("FactoryPattern_WhenToUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour créer des familles d&apos;objets liés.
        /// </summary>
        public static string FactoryPattern_WhenToUse3 {
            get {
                return ResourceManager.GetString("FactoryPattern_WhenToUse3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 Quand l&apos;utiliser.
        /// </summary>
        public static string FactoryPattern_WhenToUseTitle {
            get {
                return ResourceManager.GetString("FactoryPattern_WhenToUseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💻 Exemple de Code.
        /// </summary>
        public static string SingletonPattern_CodeTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_CodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficile à tester.
        /// </summary>
        public static string SingletonPattern_Cons1 {
            get {
                return ResourceManager.GetString("SingletonPattern_Cons1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problèmes d&apos;état global.
        /// </summary>
        public static string SingletonPattern_Cons2 {
            get {
                return ResourceManager.GetString("SingletonPattern_Cons2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Préoccupations de sécurité de thread.
        /// </summary>
        public static string SingletonPattern_Cons3 {
            get {
                return ResourceManager.GetString("SingletonPattern_Cons3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Inconvénients.
        /// </summary>
        public static string SingletonPattern_ConsTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_ConsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le pattern Singleton assure qu&apos;une classe n&apos;ait qu&apos;une seule instance et fournit un point d&apos;accès global à cette instance..
        /// </summary>
        public static string SingletonPattern_Description {
            get {
                return ResourceManager.GetString("SingletonPattern_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Description.
        /// </summary>
        public static string SingletonPattern_DescriptionTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une Instance Singleton.
        /// </summary>
        public static string SingletonPattern_InteractiveButton {
            get {
                return ResourceManager.GetString("SingletonPattern_InteractiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le bouton pour créer une instance Singleton. Remarquez que plusieurs clics retournent toujours la même instance !.
        /// </summary>
        public static string SingletonPattern_InteractiveDesc {
            get {
                return ResourceManager.GetString("SingletonPattern_InteractiveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎮 Exemple Interactif.
        /// </summary>
        public static string SingletonPattern_InteractiveTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_InteractiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garantie d&apos;instance unique.
        /// </summary>
        public static string SingletonPattern_Pros1 {
            get {
                return ResourceManager.GetString("SingletonPattern_Pros1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point d&apos;accès global.
        /// </summary>
        public static string SingletonPattern_Pros2 {
            get {
                return ResourceManager.GetString("SingletonPattern_Pros2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation paresseuse.
        /// </summary>
        public static string SingletonPattern_Pros3 {
            get {
                return ResourceManager.GetString("SingletonPattern_Pros3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✅ Avantages.
        /// </summary>
        public static string SingletonPattern_ProsTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_ProsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏗️ Singleton Pattern.
        /// </summary>
        public static string SingletonPattern_Title {
            get {
                return ResourceManager.GetString("SingletonPattern_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quand exactement une instance d&apos;une classe est nécessaire.
        /// </summary>
        public static string SingletonPattern_WhenToUse1 {
            get {
                return ResourceManager.GetString("SingletonPattern_WhenToUse1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour les gestionnaires de configuration ou services de journalisation.
        /// </summary>
        public static string SingletonPattern_WhenToUse2 {
            get {
                return ResourceManager.GetString("SingletonPattern_WhenToUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour contrôler l&apos;accès aux ressources partagées.
        /// </summary>
        public static string SingletonPattern_WhenToUse3 {
            get {
                return ResourceManager.GetString("SingletonPattern_WhenToUse3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎯 Quand l&apos;utiliser.
        /// </summary>
        public static string SingletonPattern_WhenToUseTitle {
            get {
                return ResourceManager.GetString("SingletonPattern_WhenToUseTitle", resourceCulture);
            }
        }
    }
}
